# Generated by Django 3.2.5 on 2021-07-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('concept_id', models.IntegerField(primary_key=True, serialize=False)),
                ('concept_name', models.CharField(blank=True, max_length=255, null=True)),
                ('domain_id', models.CharField(blank=True, max_length=20, null=True)),
                ('vocabulary_id', models.CharField(blank=True, max_length=20, null=True)),
                ('concept_class_id', models.CharField(blank=True, max_length=20, null=True)),
                ('standard_concept', models.CharField(blank=True, max_length=1, null=True)),
                ('concept_code', models.CharField(blank=True, max_length=50, null=True)),
                ('valid_start_date', models.DateField(blank=True, null=True)),
                ('valid_end_date', models.DateField(blank=True, null=True)),
                ('invalid_reason', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'concept',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VisitOccurrence',
            fields=[
                ('visit_occurrence_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('person_id', models.BigIntegerField(blank=True, null=True)),
                ('visit_concept_id', models.IntegerField(blank=True, null=True)),
                ('visit_start_date', models.DateField(blank=True, null=True)),
                ('visit_start_datetime', models.DateTimeField(blank=True, null=True)),
                ('visit_end_date', models.DateField(blank=True, null=True)),
                ('visit_end_datetime', models.DateTimeField(blank=True, null=True)),
                ('visit_type_concept_id', models.IntegerField(blank=True, null=True)),
                ('provider_id', models.BigIntegerField(blank=True, null=True)),
                ('care_site_id', models.BigIntegerField(blank=True, null=True)),
                ('visit_source_value', models.CharField(blank=True, max_length=50, null=True)),
                ('visit_source_concept_id', models.IntegerField(blank=True, null=True)),
                ('admitted_from_concept_id', models.IntegerField(blank=True, null=True)),
                ('admitted_from_source_value', models.CharField(blank=True, max_length=50, null=True)),
                ('discharge_to_source_value', models.CharField(blank=True, max_length=50, null=True)),
                ('discharge_to_concept_id', models.IntegerField(blank=True, null=True)),
                ('preceding_visit_occurrence_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'visit_occurrence',
                'managed': False,
            },
        ),
    ]
